---
title: "Descriptive of ES"
output: html_document
date: "2025-02-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
library(here)
library(dplyr)
library(ggplot2)

# Execute this code to upload the the function descriptive_stats()
source(here("r_scripts", "data_analysis", "03_descriptive_stats_function.R")) 
source(here("r_scripts", "data_analysis", "02_clean_data.R")) 

```

# Descriptive information of effect sizes (by type) and sample sizes 

## Cohen's d
```{r, cohen_d_stats}
reported_cohen_d <- cleaned_data %>% 
  filter(power_analysis == "a priori" &
         type_standardised_es == "Cohen's d family" &
         !is.na(magnitude_es)) %>% 
  pull(magnitude_es) 

gpower_cohen_d <- cleaned_data %>% 
  filter(power_analysis == "a priori" &
         type_es_in_gpower %in% c("Cohen's ds", "Cohen's dz") &
         !is.na(magnitude_es_in_gpower)) %>% 
  pull(magnitude_es_in_gpower)

combined_cohen_d <- c(reported_cohen_d, gpower_cohen_d)

cohen_d_stats <- descriptive_stats(combined_cohen_d)
```

## Number of Cohen's d = 0.5 
```{r, echo=FALSE}

sum(combined_cohen_d == 0.5) 

```


## ES justification for ES larger than 1
```{r, echo=FALSE}

cleaned_data %>%
  filter(power_analysis == "a priori" &
         type_standardised_es == "Cohen's d family" & 
         magnitude_es > 0.8) %>%
  select(study_title, es_justification, magnitude_es)
  
```


## Hedges' g
```{r hedges_g_stats}

hedges_g_stats <- cleaned_data %>%
  filter(power_analysis == "a priori" & 
         type_standardised_es == "Hedge's g family" &
         !is.na(magnitude_es)) %>% 
  pull(magnitude_es) %>% 
  descriptive_stats()
            
```

## Cohen's f
```{r cohen_f_stats}

reported_cohen_f <- cleaned_data %>%
  filter(power_analysis == "a priori" & 
         type_standardised_es == "Cohen's f" &
         !is.na(magnitude_es)) %>% 
  pull(magnitude_es) 

gpower_cohen_f <- cleaned_data %>%
  filter(power_analysis == "a priori" & 
         type_es_in_gpower == "Cohen's f" &
         !is.na(magnitude_es_in_gpower)) %>% 
  pull(magnitude_es_in_gpower)

combined_cohen_f <- c(reported_cohen_f, gpower_cohen_f)

cohen_f_stats <- descriptive_stats(combined_cohen_f)

```


# Number of Cohen's f = 0.25 
```{r echo=FALSE}

sum(combined_cohen_f == 0.25) 

```

## Partial eta squared
```{r partial_eta_stats}

partial_eta_stats <- cleaned_data %>%
  filter(power_analysis == "a priori" &
         type_standardised_es == "eta partial squared (ηp^2)" &
         !is.na(magnitude_es)) %>% 
  pull(magnitude_es) %>% 
  descriptive_stats()

```

```{r eta_stats}

eta_stats <- cleaned_data %>%
  filter(power_analysis == "a priori" & 
         type_standardised_es == "eta squared (η^2)" &
         !is.na(magnitude_es)) %>% 
  pull(magnitude_es) %>% 
  descriptive_stats()

```

## Sample sizes of studies used as ES justification
```{r sample_previous_study, echo=FALSE}

previous_study <- cleaned_data %>%
  select(sample_previous_study) %>%
  filter(!is.na(sample_previous_study)) %>%
  mutate(extracted_samples = stringr::str_extract_all(sample_previous_study, "\\d+")) %>% 
  unnest(extracted_samples) %>%
  mutate(extracted_samples = as.numeric(extracted_samples)) %>%
  summarise(median = median(extracted_samples),
            average = round(mean(extracted_samples), 0),
            sd = round(sd(extracted_samples), 0),
            maximum = max(extracted_samples),
            minimum = min(extracted_samples))
```

## Match between statistical test reported in a priori power analysis and 
## in study
```{r echo=FALSE}

cleaned_data %>%
  filter(power_analysis == "a priori") %>%
  select(statistical_test_power, statistical_test_study) %>%
  filter(!statistical_test_power %in% c("not reported", "unclear") &
         statistical_test_study != "unclear") %>%
  mutate(match = as.character(statistical_test_power) ==
           as.character(statistical_test_study)) %>%
  group_by(match) %>%
  summarise(n = n(), .groups = "drop") %>% 
  mutate(prop = n / sum(cleaned_data$power_analysis == "a priori")*100)

```
