---
title: "Figures"
date: "2025-01-29"
---

```{r echo=FALSE, warning = FALSE, message = FALSE}

# Load packages
library(here)
library(ggplot2)
library(dplyr)
library(patchwork)

# Load data
source(here("r_scripts", "data_analysis", "02_clean_data.R"))
```

# Reporting practices

## Type of standardised ES reported in a priori power analyses

```{r echo = FALSE}

# Create a plot for the type of standardised ES reported in a priori power analyses
  cleaned_data %>% 
  filter(power_analysis == "a priori" &
         type_es == "yes, standardised" & 
         !is.na(magnitude_es)) %>%
  group_by(type_standardised_es) %>%
  summarise(n = n()) %>%
  mutate(prop = n / sum(n) * 100) %>%
  arrange(desc(prop)) %>%
  mutate(type_es = factor(type_standardised_es, 
         levels = type_standardised_es)) %>%
  ggplot(aes(x = type_es, y = prop)) +
  geom_bar(stat = "identity", width = 0.5) +
  ylab("Proportion (%)") +
  xlab(NULL) +
  scale_y_continuous(breaks = seq(0, 50, 10), 
                     limits = c(0,50), 
                     expand = c(0,0)) +
  theme(axis.text.x = element_text(vjust = 0.5, 
                                   hjust = 0.5),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
        scale_x_discrete(labels = c("not reported", 
                                    "Cohen's f",
                                    "Cohen's d \nfamily", 
                                    "partial eta \nsquared", 
                                    "eta squared", 
                                    "Hedges' g \nfamily")) +
  theme(axis.text.x = element_text(vjust = 0.5, hjust=0.5),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.grid.major.y = element_line(color = "gray", 
                                          linetype = "solid", 
                                          linewidth = 0.3))

# save plot
ggsave(here("figures", "type_es.pdf"), width = 4, height = 4)
```

## Effect sizes justifications

```{r echo=FALSE}
cleaned_data %>% 
  filter(power_analysis == "a priori" &
         !is.na(magnitude_es)) %>% 
  select(es_justification) %>%
  mutate(es_justification = 
           case_when(es_justification %in% 
                       c("meta-analysis and previous studies",
                         "meta-analysis and previous study",
                         "previous studies") ~ "unclear",
                     es_justification %in% c("methodological paper", 
                                              "position statement", 
                                              "systematic review") ~ "others",
                     is.na(es_justification) ~ "not reported",
                     TRUE ~ es_justification)) %>%
  group_by(es_justification) %>%
  summarise(n = n()) %>%
  mutate(prop = ceiling(n / sum(n)*100)) %>%
  arrange(desc(prop)) %>%
  mutate(es_justification = factor(es_justification, 
                                   levels = es_justification)) %>%
  ggplot(aes(x = es_justification, y = prop)) +
  geom_bar(stat = "identity") +
  ylab(NULL) +
  xlab(NULL) +
  scale_y_continuous(breaks = seq(0, 60, 10), 
                     limits = c(0,60), 
                     expand = c(0,0)) +
  scale_x_discrete(labels = c("previous study" = "previous \nstudy", 
                              "not reported" = "not \nreported",
                              "Cohen's d thresholds" = "Cohen's d\nthreshold")) +
  theme(axis.text.x = element_text(vjust = 0.5, hjust=0.5),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.grid.major.y = element_line(color = "gray", 
                                          linetype = "solid", 
                                          linewidth = 0.3))

# save plot
ggsave(here("figures", "es_justification.pdf"), width = 4, height = 4)

```

## Statistical tests reported in a priori power analyses

```{r echo = FALSE}
# Create a plot for statistical tests reported in a priori power analyses
(statistical_test <- cleaned_data %>% 
  filter(power_analysis == "a priori") %>%
  mutate(test = case_when(statistical_test_power 
                          %in% c("paired t-test", 
                                 "unpaired t-test") ~"t-test",
                          statistical_test_power == "not reported" ~ 
                            "not reported",
                          statistical_test_power == "unclear" ~ 
                            "unclear",
                          TRUE ~ 'F-test')) %>%
  group_by(test) %>%
  summarise(n = n()) %>%
  mutate(freq = n*100 / base::sum(n)) %>% 
  arrange(desc(freq)) %>%
  mutate(test = factor(test, levels = test)) %>%
  ggplot(aes(x = test, y = freq)) +
  geom_bar(stat = "identity", width = 0.5) +
  ylab(NULL) +
  xlab(NULL) +
  scale_y_continuous(breaks = seq(0, 70, 10), 
                     limits = c(0,70), 
                     expand = c(0,0)) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.grid.major.y = element_line(color = "gray", 
                                          linetype = "solid", 
                                          linewidth = 0.3)))

# save plot
ggsave(here("figures", "statistical_test.pdf"), width = 4, height = 4)

```

```{r echo = FALSE}

# Combine the 3 plots in one single figure
(type_es + es_justification + statistical_test) +
  plot_annotation(tag_levels = 'a') &
  plot_layout(axes = "collect", 
              guides = "collect") 


ggsave(here("figures", "figures.pdf"), 
       width = 9, height = 4, combined_figures)

```

## Reproducibility of a priori power analyses

```{r echo = FALSE}
cleaned_data %>%
  filter(power_analysis == "a priori") %>%
  select(reproducibility) %>%
  mutate(reproducibility = if_else(reproducibility == "fully non-reproducible", 
                                                      "non-reproducible", 
                                                      reproducibility)) %>%
  group_by(reproducibility) %>%
  summarise(n = n()) %>%
  mutate(prop = n / sum(n)*100) %>%
  arrange(desc(prop)) %>%
  mutate(reproducibility = factor(reproducibility, 
                                  levels = reproducibility)) %>%
  ggplot(aes(x = reproducibility, y = prop, fill = reproducibility)) +
  geom_bar(stat = "identity", width = 0.5) +
  ylab("Porportion (%)") +
  xlab(NULL) +
  scale_y_continuous(breaks = seq(0, 100, 10), 
                     limits = c(0,100), 
                     expand = c(0,0)) +
 scale_fill_manual(values = c(
    "non-reproducible" = "#E69F00",      
    "conditionally reproducible" = "#56B4E9", 
    "reproducible" = "#009E73")
    ) +
  scale_x_discrete(labels = c("non-reproducible", 
                              "conditionally \nreproducible", 
                              "reproducible")) +
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 0.5),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.grid.major.y = element_line(color = "gray", 
                                          linetype = "solid", 
                                          linewidth = 0.3))

# save plot
ggsave(here("figures", "reproducibility.pdf"), width = 4, height = 4)
```

## Distribution of effect sizes

```{r}
es_distribution <- cleaned_data %>% 
  filter(power_analysis == "a priori" &
         type_standardised_es != "not reported" &
         !is.na(magnitude_es)) %>% 
  select(type_standardised_es, magnitude_es, es_justification) %>%
  mutate(es_justification = 
           case_when(es_justification %in% 
                       c("meta-analysis and previous studies",
                         "meta-analysis and previous study",
                         "previous studies") ~ "unclear",
                     es_justification %in% c("methodological paper", 
                                              "position statement", 
                                              "systematic review") ~ "others",
                     is.na(es_justification) ~ "not reported",
                     TRUE ~ es_justification)) %>%
  filter(es_justification != "not reported") %>%
  ggplot(aes(y = magnitude_es, x = type_standardised_es)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(aes(colour = es_justification), 
              width = 0.2, 
              size = 1, 
              alpha = 0.5) +
  scale_y_continuous(limits = c(0, 3.5), 
                     breaks = seq(0, 3.5, by = 0.5),
                     expand = c(0, 0)) +
  scale_x_discrete(labels = c("Cohen's d \nfamily", 
                              "Cohen's f",
                              "partial eta \nsquared", 
                              "eta squared", 
                              "Hedges' g \nfamily")) +
  labs(y = "Effect Size", x = NULL, colour = "Justification") +
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 0.5),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.grid.major.y = element_line(color = "gray", 
                                          linetype = "solid", 
                                          linewidth = 0.3))

ggsave(here("figures", "es_distribution.pdf"), width = 8, height = 4)
```
